language: java

env:
  global:
  - secure: ljImdd7PjxKxZkOhuqE9kRcFax1+mHYBOxYHwvrheUTIKdTujohPZx8R8spJAkL1leQSjxjfccbjHhxoYg3tbB0r+JRnllk28+i1iKPoR1tNDtwH9iUQDmNgl44vj7Q9KM1kxuuwHY4KuThWR+RfGfpwcnZbkaQMAbOO31m9u75NGWHX6Aam2loPKuD4nd/DUxhy83TYGLtiH9UMe0dY7b2XZHfsJLuM/Sp/j9UFHuQuRi+ZzLGNLSIiI2tmq3sViQU0UDJoinWg+vAVWkPZYCoh5dANW0O4gCiueQ2lIyEAch0CfZCxmIjR5kOxMIdeFnrpReKia7lGv4AGQDp7htNr6q667RF9SiQPYCPZRvmqXriyey7t3pa1JbdBByMa9oHJMqCCl/+e0695BRszkdwds1pCAJ/PIwT4QaYj4zNzIrT2EWnqsiTLGaLvX12/a4710bTVQFbmQ3HoAV1FP85IeZ/++gT1MxHk18Q1ISNUWGGIthtSbnzdHaIOxGSij0EKRmRI/Vfe+6aYDNAZhF3R1GQrVXS9HkG+RqAjO1d0k0aH+lTz/UQGf66TB+2zD4P7TLFTd/n+rtfashwsUBN8JFjAIVnxlLMWI+58kw/3iAO4UUcVUTEmxhDby4WQUbsK0U2acjB9FDqw5SquLSm+3bDmxEBWyVNPbXTvJJo=

sudo: true

script:
  - mvn test
  - mvn javadoc:javadoc

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE hyperperform;' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE public."GitPush" ( id integer NOT NULL, repository character varying(255), "timestamp" timestamp without time zone, username character varying(255), commitsize integer, url character varying(255), message character varying(255), CONSTRAINT "GitPush_pkey" PRIMARY KEY (id) ); CREATE SEQUENCE public.hibernate_sequence INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE public."TravisEvent" ( id integer NOT NULL, branch character varying(255), commiter character varying(255), repo character varying(255), status character varying(255), "timestamp" timestamp without time zone, CONSTRAINT "TravisEvent_pkey" PRIMARY KEY (id));' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE public."CalendarProject" ( projectid integer NOT NULL, calendarid character varying(255), collaborators bytea, creator character varying(255), duedate timestamp without time zone, eventid character varying(255), reponame character varying(255), "timestamp" timestamp without time zone, CONSTRAINT "CalendarProject_pkey" PRIMARY KEY (projectid));' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE public."CalendarMeeting" ( meetingid integer NOT NULL, calendarid character varying(255), creator character varying(255), duedate timestamp without time zone, eventid character varying(255), location character varying(255), "timestamp" timestamp without time zone, CONSTRAINT "CalendarMeeting_pkey" PRIMARY KEY (meetingid));' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE public."CalendarMeeting_attendees" ( "CalendarMeeting_meetingID" integer NOT NULL, attendees integer, attendees_key character varying(255) NOT NULL, CONSTRAINT "CalendarMeeting_attendees_pkey" PRIMARY KEY ("CalendarMeeting_meetingID", attendees_key), CONSTRAINT fkn4q1pmj9vx3tfsaw9irp9voax FOREIGN KEY ("CalendarMeeting_meetingID") REFERENCES public."CalendarMeeting" (meetingid) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION);' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE public."GitIssue"(id integer NOT NULL, action character varying(255), assignee character varying(255), createdby character varying(255), issueid bigint, repository character varying(255), "timestamp" timestamp without time zone, title character varying(255), url character varying(255), CONSTRAINT "GitIssue_pkey" PRIMARY KEY (id));' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE public."User" (email character varying(255) NOT NULL, gitusername character varying(255), name character varying(255), "position" integer, profilepicture bytea,  role integer, surname character varying(255), username character varying(255), password character varying(255), CONSTRAINT "User_pkey" PRIMARY KEY (email));' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE "AccessEvent"(id integer NOT NULL, email character varying(255), day bigint, deviceid character varying(255), employeeid character varying(255), name character varying(255), surname character varying(255), "timestamp" timestamp without time zone, CONSTRAINT "AccessEvent_pkey" PRIMARY KEY (id) );' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE public."ForecastData"(data character varying(10485760) NOT NULL, CONSTRAINT "ForecastData_pkey" PRIMARY KEY (data));' -U postgres

test:
  adapter: postgresql
  database: hyperperform

after_success:
  - sudo chmod 777 deploy.sh
  - sudo ./deploy.sh
  
notifications:
  slack: codusmaximus:TfshAEu8LRkjOGkyZnOQq5ys
  webhooks: https://travis.hyperperform.me